export interface ElementData {
  symbol: string;
  name: string;
  color: number;
}

// Data Map indexed by Symbol
export const ELEMENT_DATA: Record<string, ElementData> = {
  H: { symbol: "H", name: "Hydrogen", color: 0xFFFFFF },
  HE: { symbol: "HE", name: "Helium", color: 0xFFC0CB },
  LI: { symbol: "LI", name: "Lithium", color: 0xCC80FF },
  BE: { symbol: "BE", name: "Beryllium", color: 0xC2E100 },
  B: { symbol: "B", name: "Boron", color: 0xFFB5B5 },
  C: { symbol: "C", name: "Carbon", color: 0x3D3D3D },
  N: { symbol: "N", name: "Nitrogen", color: 0x3050FF },
  O: { symbol: "O", name: "Oxygen", color: 0xFF1111 },
  F: { symbol: "F", name: "Fluorine", color: 0x90FF00 },
  NE: { symbol: "NE", name: "Neon", color: 0xB3E3F5 },
  NA: { symbol: "NA", name: "Sodium", color: 0xAB5CF2 },
  MG: { symbol: "MG", name: "Magnesium", color: 0x8AFF00 },
  AL: { symbol: "AL", name: "Aluminium", color: 0xBFA6A6 },
  SI: { symbol: "SI", name: "Silicon", color: 0xF0C8A0 },
  P: { symbol: "P", name: "Phosphorus", color: 0xFF9C00 },
  S: { symbol: "S", name: "Sulfur", color: 0xFFFF30 },
  CL: { symbol: "CL", name: "Chlorine", color: 0x1FF01F },
  AR: { symbol: "AR", name: "Argon", color: 0x80D1E3 },
  K: { symbol: "K", name: "Potassium", color: 0x8F40D4 },
  CA: { symbol: "CA", name: "Calcium", color: 0x3DFF00 },
  SC: { symbol: "SC", name: "Scandium", color: 0xE6E6E6 },
  TI: { symbol: "TI", name: "Titanium", color: 0x909090 },
  V: { symbol: "V", name: "Vanadium", color: 0xA6A6AB },
  CR: { symbol: "CR", name: "Chromium", color: 0x8A99C7 },
  MN: { symbol: "MN", name: "Manganese", color: 0x9C7AC7 },
  FE: { symbol: "FE", name: "Iron", color: 0xE06633 },
  CO: { symbol: "CO", name: "Cobalt", color: 0xF090A0 },
  NI: { symbol: "NI", name: "Nickel", color: 0x50D050 },
  CU: { symbol: "CU", name: "Copper", color: 0xC88033 },
  ZN: { symbol: "ZN", name: "Zinc", color: 0x7D80B0 },
  GA: { symbol: "GA", name: "Gallium", color: 0xC28F8F },
  GE: { symbol: "GE", name: "Germanium", color: 0x668F8F },
  AS: { symbol: "AS", name: "Arsenic", color: 0xBD80E3 },
  SE: { symbol: "SE", name: "Selenium", color: 0xFFA100 },
  BR: { symbol: "BR", name: "Bromine", color: 0xA62929 },
  KR: { symbol: "KR", name: "Krypton", color: 0x5CB8D1 },
  RB: { symbol: "RB", name: "Rubidium", color: 0x702EB0 },
  SR: { symbol: "SR", name: "Strontium", color: 0x00FF00 },
  Y: { symbol: "Y", name: "Yttrium", color: 0x94FFFF },
  ZR: { symbol: "ZR", name: "Zirconium", color: 0x94E3E3 },
  NB: { symbol: "NB", name: "Niobium", color: 0x73C2C9 },
  MO: { symbol: "MO", name: "Molybdenum", color: 0x54B5B5 },
  TC: { symbol: "TC", name: "Technetium", color: 0x3B9E9E },
  RU: { symbol: "RU", name: "Ruthenium", color: 0x248F8F },
  RH: { symbol: "RH", name: "Rhodium", color: 0x0A7D8C },
  PD: { symbol: "PD", name: "Palladium", color: 0x006985 },
  AG: { symbol: "AG", name: "Silver", color: 0xC0C0C0 },
  CD: { symbol: "CD", name: "Cadmium", color: 0xFFD98F },
  IN: { symbol: "IN", name: "Indium", color: 0xA67573 },
  SN: { symbol: "SN", name: "Tin", color: 0x668080 },
  SB: { symbol: "SB", name: "Antimony", color: 0x9E63B5 },
  TE: { symbol: "TE", name: "Tellurium", color: 0xD47A00 },
  I: { symbol: "I", name: "Iodine", color: 0x9400D3 },
  XE: { symbol: "XE", name: "Xenon", color: 0x429EB0 },
  CS: { symbol: "CS", name: "Caesium", color: 0x57178F },
  BA: { symbol: "BA", name: "Barium", color: 0x00C900 },
  LA: { symbol: "LA", name: "Lanthanum", color: 0x70D4FF },
  CE: { symbol: "CE", name: "Cerium", color: 0xFFFFC7 },
  PR: { symbol: "PR", name: "Praseodymium", color: 0xD9FFC7 },
  ND: { symbol: "ND", name: "Neodymium", color: 0xC7FFC7 },
  PM: { symbol: "PM", name: "Promethium", color: 0xA3FFC7 },
  SM: { symbol: "SM", name: "Samarium", color: 0x8FFFC7 },
  EU: { symbol: "EU", name: "Europium", color: 0x61FFC7 },
  GD: { symbol: "GD", name: "Gadolinium", color: 0x45FFC7 },
  TB: { symbol: "TB", name: "Terbium", color: 0x30FFC7 },
  DY: { symbol: "DY", name: "Dysprosium", color: 0x1FFFFC7 },
  HO: { symbol: "HO", name: "Holmium", color: 0x00FF9C },
  ER: { symbol: "ER", name: "Erbium", color: 0x00E675 },
  TM: { symbol: "TM", name: "Thulium", color: 0x00D452 },
  YB: { symbol: "YB", name: "Ytterbium", color: 0x00BF38 },
  LU: { symbol: "LU", name: "Lutetium", color: 0x00AB24 },
  HF: { symbol: "HF", name: "Hafnium", color: 0x4DB2FF },
  TA: { symbol: "TA", name: "Tantalum", color: 0x4DA6FF },
  W: { symbol: "W", name: "Tungsten", color: 0x2194D6 },
  RE: { symbol: "RE", name: "Rhenium", color: 0x267DAB },
  OS: { symbol: "OS", name: "Osmium", color: 0x266696 },
  IR: { symbol: "IR", name: "Iridium", color: 0x175487 },
  PT: { symbol: "PT", name: "Platinum", color: 0xD0D0E0 },
  AU: { symbol: "AU", name: "Gold", color: 0xFFD700 },
  HG: { symbol: "HG", name: "Mercury", color: 0xB8B8D0 },
  TL: { symbol: "TL", name: "Thallium", color: 0xA6544D },
  PB: { symbol: "PB", name: "Lead", color: 0x575961 },
  BI: { symbol: "BI", name: "Bismuth", color: 0x9E4FB5 },
  PO: { symbol: "PO", name: "Polonium", color: 0xAB5C00 },
  AT: { symbol: "AT", name: "Astatine", color: 0x754F45 },
  RN: { symbol: "RN", name: "Radon", color: 0x428296 },
  FR: { symbol: "FR", name: "Francium", color: 0x420066 },
  RA: { symbol: "RA", name: "Radium", color: 0x007D00 },
  AC: { symbol: "AC", name: "Actinium", color: 0x70ABFA },
  TH: { symbol: "TH", name: "Thorium", color: 0x00BAFF },
  PA: { symbol: "PA", name: "Protactinium", color: 0x00A1FF },
  U: { symbol: "U", name: "Uranium", color: 0x008FFF },
  NP: { symbol: "NP", name: "Neptunium", color: 0x0080FF },
  PU: { symbol: "PU", name: "Plutonium", color: 0x006BFF },
  AM: { symbol: "AM", name: "Americium", color: 0x545CF2 },
  CM: { symbol: "CM", name: "Curium", color: 0x785CE3 },
  BK: { symbol: "BK", name: "Berkelium", color: 0x8A4FE3 },
  CF: { symbol: "CF", name: "Californium", color: 0xA136D4 },
  ES: { symbol: "ES", name: "Einsteinium", color: 0xB31FD4 },
  FM: { symbol: "FM", name: "Fermium", color: 0xB31FBA },
  MD: { symbol: "MD", name: "Mendelevium", color: 0xB30DA6 },
  NO: { symbol: "NO", name: "Nobelium", color: 0xBD0D87 },
  LR: { symbol: "LR", name: "Lawrencium", color: 0xC70066 },
  RF: { symbol: "RF", name: "Rutherfordium", color: 0xCC0059 },
  DB: { symbol: "DB", name: "Dubnium", color: 0xD1004F },
  SG: { symbol: "SG", name: "Seaborgium", color: 0xD90045 },
  BH: { symbol: "BH", name: "Bohrium", color: 0xE00038 },
  HS: { symbol: "HS", name: "Hassium", color: 0xE6002E },
  MT: { symbol: "MT", name: "Meitnerium", color: 0xEB0024 },
  DS: { symbol: "DS", name: "Darmstadtium", color: 0xFF001F },
  RG: { symbol: "RG", name: "Roentgenium", color: 0xFF001F },
  CN: { symbol: "CN", name: "Copernicium", color: 0xFF001F },
  NH: { symbol: "NH", name: "Nihonium", color: 0xFF001F },
  FL: { symbol: "FL", name: "Flerovium", color: 0xFF001F },
  MC: { symbol: "MC", name: "Moscovium", color: 0xFF001F },
  LV: { symbol: "LV", name: "Livermorium", color: 0xFF001F },
  TS: { symbol: "TS", name: "Tennessine", color: 0xFF001F },
  OG: { symbol: "OG", name: "Oganesson", color: 0xFF001F }
};

// Helper Map to find by Name (e.g., if user searches "Hydrogen")
export const ELEMENT_BY_NAME: Record<string, ElementData> = Object.values(ELEMENT_DATA).reduce((acc, el) => {
  acc[el.name.toUpperCase()] = el;
  return acc;
}, {} as Record<string, ElementData>);

// Getter logic
export const getElementInfo = (query: string): ElementData | undefined => {
  const q = query.toUpperCase();
  return ELEMENT_DATA[q] || ELEMENT_BY_NAME[q];
};